apiVersion: v1
kind: Template
labels:
  template: nexus3-template
metadata:
  annotations:
    description: Sonatype Nexus 3 template
    tags: ci,nexus
  name: nexus3
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/sonatype/nexus3:${NEXUS_VERSION}
      name: ${NEXUS_VERSION}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 0
        timeoutSeconds: 1200
        updatePeriodSeconds: 1
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: ${SERVICE_NAME}
            command:
              - "/bin/bash"
              - "-c"
              - "curl -o /tmp/nexus-functions -s https://raw.githubusercontent.com/faust64/nexus/master/scripts/nexus-functions; source /tmp/nexus-functions; add_nexus3_redhat_repos admin admin123 http://${SERVICE_NAME}:8081; if test \"$HTTP_PROXY\"; then add_nexus3_proxy admin admin123 http://${SERVICE_NAME}:8081; fi"
            env:
            - name: HTTP_PROXY
              value: "${HTTP_PROXY}"
            - name: HTTPS_PROXY
              value: "${HTTPS_PROXY}"
            - name: NO_PROXY
              value: "${NO_PROXY}"
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: CONTEXT_PATH
            value: /
          - name: HOME
            value: /nexus-data
          - name: INSTALL4J_ADD_VM_PARAMS
            value: ${JAVA_ARGS} -Djava.util.prefs.userRoot=/nexus-data/javaprefs
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - reply=`curl -s -o /dev/null -w %{http_code} "http://127.0.0.1:8081/static/css/nexus-content.css"`;
                if test "$reply" -lt 200 -o "$reply" -ge 400; then exit 1; elif ! ls /nexus-data; then exit 2; fi
            failureThreshold: 60
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /static/css/nexus-content.css
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          volumeMounts:
          - mountPath: /nexus-data
            name: data
        volumes:
        - name: data
          emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:${NEXUS_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${SERVICE_NAME}
      weight: 100
parameters:
- description: CPU Limit
  displayName: Nexus CPU Limit
  name: CPU_LIMIT
  value: 500m
- description: CPU Request
  displayName: Nexus CPU Request
  name: CPU_REQUEST
  value: 200m
- name: HTTP_PROXY
- name: HTTPS_PROXY
- description: Java Arguments
  displayName: JAVA_ARGS
  name: JAVA_ARGS
  value: -Xms1400m -Xmx1400m -XX:MaxDirectMemorySize=2g
- description: Memory Limit
  displayName: Nexus Memory Limit
  name: MEMORY_LIMIT
  value: 4200Mi
- description: Memory Request
  displayName: Nexus Memory Request
  name: MEMORY_REQUEST
  value: 3800Mi
- displayName: Sonatype Nexus version
  name: NEXUS_VERSION
  required: true
  value: 3.13.0
- name: NO_PROXY
- displayName: Sonatype Nexus Service Name
  name: SERVICE_NAME
  required: true
  value: nexus
